[project]

name = "control"
version = "0.9.0dev"
description = "A library for solving certain PDE-constrained optimization problems"
readme = "README.md"
maintainers = [
    {name="Santolo Leveque"}
]
dependencies = [
    "firedrake",
    "matplotlib"
]
optional-dependencies.test = [
    "numpy",
    "pytest"
]

[tool.setuptools]

packages = [
    "control"
]

[tool.pytest.ini_options]

markers = [
    "large: tests which use a large amount of memory"]

[tool.ruff.lint]

ignore = ["E501", "F403", "F405"]
preview = true
select = ["E", "EXE", "F", "PIE", "UP", "W"]
